### ISSUE TITLE
x86_64-pc-windows-gnu triggers  #[cfg(any(unix, target_env = "gnu"))]

### ISSUE THREAD

**Issue by Flat** [Lakelezz/audiopus_sys#6]
This causes the build to fail as it uses the gnu `cp` utility to copy the source files before building. this should either be changed to `all` instead of `any` or gated inside the same config to handle the windows gnu target that may not have any gnu utilities.

**Comment by Lakelezz** [comment]
Thank you for raising this issue.

The utility to copy the Opus project has been removed in the upcoming version, which remedies this.
